import { DashboardData } from './DashboardTypes';

export const energyOilGasDemoScenario: DashboardData = {
  context: {
    company: 'Teranga Energy Operations',
    sector: 'Gaz / Pétrole / Énergie',
    period: '30 derniers jours',
    activeSite: 'Tous les sites',
    services: ['Exploitation gaz', 'Maintenance mécanique', 'HSE', 'Logistique', 'Procédés'],
    readingMode: 'essential',
  },
  score: {
    value: 40,
    max: 100,
    level: 'Action urgente',
    trend: '↘ -8 pts vs période précédente',
    situation: 'action_urgente',
    explanationEssential: 'Situation nécessitant une action rapide sur incidents critiques, actions en retard et NC ouvertes.',
    explanationExpert: 'Le score est pénalisé par les actions en retard, les incidents critiques, les NC ouvertes et des preuves ISO manquantes.',
    factors: [
      { label: 'Actions en retard' },
      { label: 'Incidents critiques' },
      { label: 'NC ouvertes' },
      { label: 'Preuves ISO manquantes' },
    ],
  },
  periods: ['30 derniers jours', 'Trimestre en cours', '6 derniers mois'],
  sites: ['Tous les sites', 'Terminal gazier de Mbao', 'Unité traitement gaz', 'Dépôt hydrocarbures'],
  services: ['Tous les services', 'Exploitation gaz', 'Maintenance mécanique', 'HSE', 'Logistique', 'Procédés'],
  kpis: [
    { id: 'inc', title: 'Incidents critiques', value: 2, description: 'Événements critiques ouverts', trend: '+1 vs période précédente', trendDirection: 'up', status: 'Urgent', severity: 'danger', recommendedAction: 'Sécuriser les zones et clôturer les analyses', whyImportant: 'Impact direct sécurité et continuité opérationnelle.', source: 'Scénario démo incidents', impactedItems: ['Compresseur C-204', 'Zone ATEX dépôt'] },
    { id: 'act', title: 'Actions en retard', value: 19, description: 'Actions CAPA dépassées', trend: '+4 en 30 jours', trendDirection: 'up', status: 'Sous tension', severity: 'warning', recommendedAction: 'Arbitrer les interventions sous 24-48h', whyImportant: 'Augmente le risque de récurrence des écarts.', source: 'Scénario démo plan d’actions', impactedItems: ['Maintenance LC-17', 'Correctifs consignation'] },
    { id: 'nc', title: 'NC ouvertes', value: 11, description: 'Non-conformités actives', trend: '+2 vs période précédente', trendDirection: 'up', status: 'Vigilance', severity: 'warning', recommendedAction: 'Prioriser la clôture des NC avec preuves', whyImportant: 'Bloque la readiness audit et la maîtrise opérationnelle.', source: 'Scénario démo NC', impactedItems: ['Permis ATEX', 'Traçabilité intervention'] },
    { id: 'risk', title: 'Risques critiques', value: 6, description: 'Risques critiques non maîtrisés', trend: 'Stable', trendDirection: 'flat', status: 'À contenir', severity: 'danger', recommendedAction: 'Renforcer les barrières terrain', whyImportant: 'Exposition forte sur sites sensibles.', source: 'Scénario démo risques', impactedItems: ['Consignation énergie', 'Coactivité'] },
    { id: 'fds', title: 'FDS à réviser', value: 8, description: 'FDS proches échéance', trend: '+2 en 30 jours', trendDirection: 'up', status: 'Planifier', severity: 'warning', recommendedAction: 'Mettre à jour les FDS prioritaires', whyImportant: 'Conformité réglementaire chimique.', source: 'Scénario démo documentaire', impactedItems: ['Méthanol hydrate', 'Additifs traitement'] },
    { id: 'audit', title: 'Audits à planifier', value: 3, description: 'Audits ciblés à programmer', trend: 'Stable', trendDirection: 'flat', status: 'À cadrer', severity: 'info', recommendedAction: 'Planifier les audits terrain ciblés', whyImportant: 'Conditionne la trajectoire ISO/SMI.', source: 'Scénario démo audits', impactedItems: ['Consignation', 'Utilités vapeur'] },
  ],
  heroMetrics: [
    { id: 'inc_critical', label: 'Incidents critiques', value: 2, status: 'Urgent', tone: 'danger' },
    { id: 'actions_late', label: 'Actions en retard', value: 19, status: 'Sous tension', tone: 'warning' },
    { id: 'nc_open', label: 'NC ouvertes', value: 11, status: 'Vigilance', tone: 'warning' },
    { id: 'iso_missing', label: 'Preuves ISO manquantes', value: 6, status: 'À compléter', tone: 'info' },
  ],
  priorities: [
    { id: 'p1', type: 'Incident', title: 'Fuite gaz détectée sur bride HP compresseur C-204', site: 'Terminal gazier de Mbao', service: 'Exploitation gaz', severity: 'danger', ageOrDue: 'Il y a 2h', sourceModule: 'Incidents', recommendedAction: 'Sécuriser zone + analyse immédiate', actionLabel: 'Ouvrir' },
    { id: 'p2', type: 'Action', title: 'Remplacer joint d’étanchéité sur ligne condensats LC-17', site: 'Unité traitement gaz', service: 'Maintenance mécanique', severity: 'warning', ageOrDue: 'Retard de 12 jours', sourceModule: 'Plan d’actions', recommendedAction: 'Arbitrer intervention sous 24h', actionLabel: 'Ouvrir' },
    { id: 'p3', type: 'NC', title: 'Permis de travail incomplet avant intervention en zone ATEX', site: 'Dépôt hydrocarbures', service: 'HSE / Maintenance', severity: 'danger', ageOrDue: 'Ouverte depuis 18 jours', sourceModule: 'Non-conformités', recommendedAction: 'Bloquer intervention jusqu’à validation', actionLabel: 'Ouvrir' },
    { id: 'p4', type: 'FDS', title: 'FDS méthanol injection hydrate à réviser', site: 'Station compression gaz', service: 'Procédés', severity: 'warning', ageOrDue: 'Échéance dans 3 jours', sourceModule: 'Documents / FDS', recommendedAction: 'Mettre à jour FDS + consignes terrain', actionLabel: 'Ouvrir' },
    { id: 'p5', type: 'Audit', title: 'Planifier audit ciblé consignation / énergie dangereuse', site: 'Raffinerie / utilités vapeur', service: 'Exploitation', severity: 'warning', ageOrDue: 'Avant le 28 mai', sourceModule: 'Audits', recommendedAction: 'Planifier audit terrain', actionLabel: 'Ouvrir' },
  ],
  insights: [
    { id: 'i1', kind: 'derive', explanation: 'NC concentrées sur dépôt hydrocarbures.', confidence: 'Élevée (89%)', source: 'Croisement NC/site', recommendedAction: 'Déployer une revue locale avec responsable de dépôt.' },
    { id: 'i2', kind: 'tendance', explanation: 'File d’actions maintenance qui vieillit.', confidence: 'Moyenne (76%)', source: 'Historique CAPA maintenance', recommendedAction: 'Arbitrer les actions > 10 jours en comité hebdomadaire.' },
    { id: 'i3', kind: 'anomalie', explanation: 'Hausse des quasi-accidents lors des consignations.', confidence: 'Moyenne (72%)', source: 'Retours terrain', recommendedAction: 'Renforcer briefing sécurité et vérification LOTO.' },
    { id: 'i4', kind: 'derive', explanation: 'Preuves ISO 45001 manquantes sur permis de travail.', confidence: 'Élevée (85%)', source: 'Pré-audit SMI', recommendedAction: 'Compléter les preuves critiques avant audit readiness.' },
  ],
  decisions: [
    { id: 'd1', title: 'Sécuriser le terminal de Mbao', impact: 'Réduction immédiate du risque critique', delay: '0-24h', owner: 'Responsable exploitation gaz' },
    { id: 'd2', title: 'Arbitrer backlog maintenance', impact: 'Réduction des retards CAPA', delay: '24-48h', owner: 'Responsable maintenance' },
  ],
  incidentTrend6m: [3, 4, 5, 4, 6, 8],
  workload: { incidents: 23, actions: 64, nc: 27 },
  severitySplit: [{ label: 'Critique', value: 10 }, { label: 'Élevée', value: 18 }, { label: 'Moyenne', value: 22 }, { label: 'Faible', value: 12 }],
  actionStatus: [{ label: 'À faire', value: 22 }, { label: 'En cours', value: 27 }, { label: 'Bloquée', value: 10 }, { label: 'Terminée', value: 18 }],
  isoOverview: [
    { standard: 'ISO 45001', readiness: 68, missingEvidence: 4, suggestedControl: 'Compléter preuves permis de travail et consignation' },
    { standard: 'ISO 14001', readiness: 79, missingEvidence: 2, suggestedControl: 'Mettre à jour suivi déchets hydrocarbures' },
    { standard: 'ISO 9001', readiness: 82, missingEvidence: 2, suggestedControl: 'Consolider la traçabilité des interventions' },
  ],
  extendedIndicators: [
    { label: 'Habilitations expirées', value: '14', status: 'À renouveler' },
    { label: 'Sous-traitants à évaluer', value: '7', status: 'Vigilance' },
    { label: 'Permis actifs', value: '36', status: 'Sous contrôle' },
    { label: 'FDS à réviser', value: '8', status: 'Prioritaire' },
    { label: 'Conformité multi-sites', value: '76%', status: 'Vigilance renforcée' },
  ],
  recentActivity: [
    { id: 'a1', label: 'Incident déclaré : fuite sur compresseur C-204' },
    { id: 'a2', label: 'Action réassignée : joint LC-17 vers équipe maintenance de garde' },
    { id: 'a3', label: 'Audit planifié : consignation / énergie dangereuse' },
    { id: 'a4', label: 'Synchronisation terrain effectuée sur terminal de Mbao' },
    { id: 'a5', label: 'Document FDS importé : méthanol injection hydrate' },
  ],
};
